import re
import csv


def clean_dasm_listing(input_file, output_file):
    # Matches the strict sequence generated by dasm:
    # Line Number -> Address -> Optional ???? -> Optional Hex Dump (up to 4 bytes + optional *)
    prefix_pattern = re.compile(
        r'^(\s*\d+\s+[a-fA-F0-9]{4}(?:\s+\?\?\?\?)?(?:\s+[a-fA-F0-9]{2}(?:\s+[a-fA-F0-9]{2}){0,3}\*?)?)'
    )

    # Standard 6502 opcodes + common dasm pseudo-ops
    mnemonics = {
        'ADC', 'AND', 'ASL', 'BCC', 'BCS', 'BEQ', 'BIT', 'BMI', 'BNE', 'BPL',
        'BRK', 'BVC', 'BVS', 'CLC', 'CLD', 'CLI', 'CLV', 'CMP', 'CPX', 'CPY',
        'DEC', 'DEX', 'DEY', 'EOR', 'INC', 'INX', 'INY', 'JMP', 'JSR', 'LDA',
        'LDX', 'LDY', 'LSR', 'NOP', 'ORA', 'PHA', 'PHP', 'PLA', 'PLP', 'ROL',
        'ROR', 'RTI', 'RTS', 'SBC', 'SEC', 'SED', 'SEI', 'STA', 'STX', 'STY',
        'TAX', 'TAY', 'TSX', 'TXA', 'TXS', 'TYA',
        'EQU', 'ORG', 'HEX', 'MAC', 'ENDM', 'SUBROUTINE', 'PROCESSOR',
        'INCLUDE', 'SEG', 'SEG.U', 'DC.B', 'DC.W', 'DS.B', 'DS.W',
        'BYTE', 'WORD', 'BYTE.B', 'WORD.W', 'ALIGN', 'REND', 'ECHO', 'ERR'
    }

    with open(input_file, 'r') as f_in, open(output_file, 'w', newline='') as f_out:
        writer = csv.writer(f_out, delimiter='\t')
        # Added an 'Unresolved' column to cleanly catch the '????' markers
        writer.writerow(['Line', 'Address', 'Unresolved', 'Hex Dump', 'Label', 'Instruction', 'Operand', 'Comment'])

        for line in f_in:
            if line.startswith('-------') or not line.strip():
                continue

            # 1. Isolate the assembler-generated prefix from the original source code
            match = prefix_pattern.match(line)
            if not match:
                continue

            prefix_str = match.group(1)
            source_str = line[match.end():].strip()

            # 2. Parse the Prefix into columns
            prefix_parts = prefix_str.split()
            line_num = prefix_parts[0]
            address = prefix_parts[1]

            unresolved = ""
            hex_dump_parts = prefix_parts[2:]
            if hex_dump_parts and hex_dump_parts[0] == '????':
                unresolved = hex_dump_parts.pop(0)

            hex_dump = " ".join(hex_dump_parts)

            # 3. Strip comments
            comment = ""
            if ';' in source_str:
                parts = source_str.split(';', 1)
                code_str = parts[0]
                comment = ';' + parts[1].strip()
            else:
                code_str = source_str

            # 4. Parse Source Code logically using the mnemonic dictionary
            tokens = code_str.split()
            label, instr, operand = "", "", ""

            if tokens:
                # If token 0 is a known instruction (e.g. "LDA", "HEX"), there is no label
                if tokens[0].upper() in mnemonics:
                    instr = tokens[0]
                    operand = " ".join(tokens[1:])
                # If token 1 is a known instruction (e.g. "BUTN0 EQU"), token 0 is the label
                elif len(tokens) > 1 and tokens[1].upper() in mnemonics:
                    label = tokens[0]
                    instr = tokens[1]
                    operand = " ".join(tokens[2:])
                # Fallback for unrecognized macros/instructions
                else:
                    label = tokens[0]
                    if len(tokens) > 1:
                        instr = tokens[1]
                        operand = " ".join(tokens[2:])

            writer.writerow([line_num, address, unresolved, hex_dump, label, instr, operand, comment])


clean_dasm_listing('reference/lode_runner_reveng/main.lst', 'reference/lode_runner_reveng/listing_clean.tsv')
